"""Add icon and tags to master data

Revision ID: 615f5e3347e4
Revises: 92cb5f44fee5
Create Date: 2025-01-24 11:12:22.659159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615f5e3347e4'
down_revision = '92cb5f44fee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=100), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_people_email', ['email'])

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_preferences_user_id', ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_preferences_user_id', type_='unique')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('uq_people_email', type_='unique')
        batch_op.alter_column('gender',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('tags')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
